CREATE TABLE IF NOT EXISTS Pouzivatel (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meno TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    hesloHash TEXT NOT NULL,
    hesloSalt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Session (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pouzivatelId INTEGER NOT NULL,
    sessionId TEXT NOT NULL,
    FOREIGN KEY (pouzivatelId) REFERENCES Pouzivatel(id)
);

CREATE TABLE IF NOT EXISTS Otazka (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Odpoved (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    otazkaId INTEGER NOT NULL,
    text TEXT NOT NULL,
    jeSpravna INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (otazkaId) REFERENCES Otazka(id)
);

CREATE TABLE IF NOT EXISTS Kviz (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pouzivatelId INTEGER NOT NULL,
    datum DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pouzivatelId) REFERENCES Pouzivatel(id)
);

CREATE TABLE IF NOT EXISTS KvizOdpoved (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kvizId INTEGER NOT NULL,
    otazkaId INTEGER NOT NULL,
    odpovedId INTEGER,
    FOREIGN KEY (kvizId) REFERENCES Kviz(id),
    FOREIGN KEY (otazkaId) REFERENCES Otazka(id),
    FOREIGN KEY (odpovedId) REFERENCES Odpoved(id)
);

CREATE TABLE IF NOT EXISTS Obrazok (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    otazkaId INTEGER NOT NULL,
    subor TEXT NOT NULL,
    FOREIGN KEY (otazkaId) REFERENCES Otazka(id)
);
